// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepoLab3.Models.DataContext;

namespace curs_2_webapi.Migrations
{
    [DbContext(typeof(TaskuriDbContext))]
    partial class TaskuriDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RepoLab3.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Important");

                    b.Property<int?>("TaskulId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("TaskulId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("RepoLab3.Models.Taskul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ClosedAt");

                    b.Property<DateTime>("DateAdded");

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("Description");

                    b.Property<int>("Status");

                    b.Property<int>("TaskImportance");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Taskuri");
                });

            modelBuilder.Entity("RepoLab3.Models.Comment", b =>
                {
                    b.HasOne("RepoLab3.Models.Taskul", "Taskul")
                        .WithMany("Comments")
                        .HasForeignKey("TaskulId");
                });
#pragma warning restore 612, 618
        }
    }
}
